#!/usr/bin/env bash
# Configuration script

sudo rm /etc/nginx/sites-available/default
sudo touch /etc/nginx/sites-available/default

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
}
" > /etc/nginx/sites-available/default

service nginx restart
